config/routes.rb
Rails.application.routes.draw do
  get "categories/index"
  get "products/index"
  get "products/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :products, only: %i[index show]
  resources :categories, only: %i[index]

  devise_for :users
  root "products#index" # Вказуємо головну сторінку

  namespace :admin do
    get "orders/index"
    get "orders/update"
    get "orders/destroy"
    get "categories/new"
    get "categories/create"
    get "products/new"
    get "products/create"
    resources :products, only: %i[new create]
    resources :categories, only: %i[new create]
  end

  resources :cart_items, only: %i[create destroy update]
  resource :cart, only: %i[show]

  resources :products, only: %i[show] do
    resources :reviews, only: %i[create edit update]
  end

  namespace :admin do
    resources :reviews, only: [:update]
  end

  resources :feedbacks, only: [:new, :create]

  resources :orders, only: [:new, :create, :show]

  get "/nova_poshta/branches", to: "nova_poshta#branches"
  get "/nova_poshta/cities", to: "nova_poshta#cities"

  namespace :admin do
    resources :orders, only: [:index, :update, :destroy, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  validates :quantity, numericality: { greater_than: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  has_many_attached :images

  validates :subject, presence: true, length: { maximum: 100 }
  validates :message, presence: true, length: { minimum: 10 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :delivery_method, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true, inclusion: { in: %w[pending sent completed canceled] }

  before_validation :set_default_status, on: :create

  private

  def set_default_status
    self.status ||= 'pending'
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, numericality: { greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  # has_many :reviews

  has_one_attached :image

  has_many :reviews, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :weight, numericality: { greater_than: 0 }, allow_nil: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many_attached :images

  validates :rating, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
  validates :content, presence: true, length: { minimum: 10 }

  validates :admin_response, length: { maximum: 500 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Оголошуємо ролі
  # for Rails 8.0
  enum :role, { user: 0, admin: 1 }

  # for other -v
  # enum role: { user: 0, admin: 1 }

  after_initialize :set_default_role, if: :new_record?

  private

    def set_default_role
    self.role ||= :user
  end

  has_one :cart, dependent: :destroy

  after_create :initialize_cart

  def initialize_cart
    create_cart
  end

  has_many :reviews, dependent: :destroy

  has_many :orders, dependent: :destroy

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Sweetie" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>

<body>
<!-- Навігаційна панель -->
<nav class="navbar">
  <div class="container">
    <div class="nav-left">
      <%= link_to 'Головна', root_path, class: 'nav-link' %>
      <% if user_signed_in? %>
        <% if current_user.user? %>
          <%= link_to 'Зворотній зв’язок', new_feedback_path, class: 'nav-link' %>
        <% end %>
        <% if current_user.admin? %>
          <%= link_to 'Замовлення', admin_orders_path, class: 'nav-link' %>
          <%= link_to 'Додати товар', new_admin_product_path, class: 'nav-link' %>
          <%= link_to 'Додати категорію', new_admin_category_path, class: 'nav-link' %>
        <% end %>
      <% end %>

    </div>

    <div class="nav-right">
      <% if user_signed_in? %>
        <% if current_user.user? %>
          <span class="user-greeting">Привіт, <%= current_user.email %>!</span>
          <%= link_to 'Кошик', cart_path, class: 'nav-link' %>
        <% end %>
        <% if current_user.admin? %>
          <span class="user-greeting">Привіт адмін, пора працювати!</span>
        <% end %>
        <%= button_to 'Вийти', destroy_user_session_path, method: :delete, class: 'nav-link logout-link' %>
      <% else %>
        <%= link_to 'Увійти', new_user_session_path, class: 'nav-link' %>
        <%= link_to 'Реєстрація', new_user_registration_path, class: 'nav-link' %>
      <% end %>
    </div>
  </div>
</nav>

<!-- Основний вміст -->
<main class="content">
<!--  <p class="notice"><%#= notice %></p>-->
<!--  <p class="alert"><%#= alert %></p>-->
  <%= yield %>
</main>
</body>
</html>